function[Gane_]=validador(Gato,Orden)
    Gane_=0;
    
    switch( mod(Orden,2)  )
        case{0}%Persona
            if( (Gato(1)==1) && (Gato(2)==1) && (Gato(3)==1) ||...
                (Gato(4)==1) && (Gato(5)==1) && (Gato(6)==1) ||...
                (Gato(7)==1) && (Gato(8)==1) && (Gato(9)==1) ||...
                (Gato(1)==1) && (Gato(4)==1) && (Gato(7)==1) ||...
                (Gato(2)==1) && (Gato(5)==1) && (Gato(8)==1) ||...
                (Gato(3)==1) && (Gato(6)==1) && (Gato(9)==1) ||...
                (Gato(1)==1) && (Gato(5)==1) && (Gato(9)==1) ||...
                (Gato(3)==1) && (Gato(5)==1) && (Gato(7)==1) )
                disp('Humano gana')
                Gane_=1;
            end
        case{1}%Maquina
            if( (Gato(1)==2) && (Gato(2)==2) && (Gato(3)==2) ||...
                (Gato(4)==2) && (Gato(5)==2) && (Gato(6)==2) ||...
                (Gato(7)==2) && (Gato(8)==2) && (Gato(9)==2) ||...
                (Gato(1)==2) && (Gato(4)==2) && (Gato(7)==2) ||...
                (Gato(2)==2) && (Gato(5)==2) && (Gato(8)==2) ||...
                (Gato(3)==2) && (Gato(6)==2) && (Gato(9)==2) ||...
                (Gato(1)==2) && (Gato(5)==2) && (Gato(9)==2) ||...
                (Gato(3)==2) && (Gato(5)==2) && (Gato(7)==2) )
                disp('CPU gana')
                Gane_=2;
            end
    end

end